
plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

version = '4.6'

application {
    // Define the main class for the application.
    mainClass = 'Mars'
}

javafx {
    modules = ['javafx.controls']
}

dependencies {
    implementation 'com.formdev:flatlaf:3.7'
}

java {
    withJavadocJar()
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

javadoc {
}

jar {
    // From FrostWire's build.gradle for desktop.
    // It seems like it came from https://stackoverflow.com/a/60669623 and was
    // later modified to work with newer versions of Gradle.
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }

    manifest {
        attributes['Implementation-Title'] = project.name
        attributes['Implementation-Version'] = project.version
        attributes['Main-Class'] = application.mainClass
    }
}
